# To execute this docker-compose yml file use `docker-compose up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome-debug:3.141.59
    container_name: chrome-browser
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=3
      - NODE_MAX_SESSION=3
    ports:
      - "5900"

  firefox:
    image: selenium/node-firefox-debug
    container_name: firefox-browser
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=3
      - NODE_MAX_SESSION=3
    ports:
      - "5900"

  hub:
    image: selenium/hub
    container_name: hub
    ports:
      - "4444:4444"